### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by vincentGuerlais** [AmoebaTeamIPG/website#1]
# To do

## Global changes
- [x] Change tab name

## Axis
- [x] Rename Axes to Axis

## Team
- [x] Add Alexis to former members
- [x] Add Mirna to former members
- [x] Add Yann to former members
- [x] Add Celia to former members
- [x] Change Bio Police size
- [x] Remove Space in Youri's description

## Project
  - [ ] Add image
  - [x] Change table order
  
## Fun at lab
  - [ ] Add description to photos

## Ideas
 - [ ] New page : image gallery
 - [ ] Pages in french
